package auk.platform.js

/** The `--mcp-call` helper: a lightweight stdio↔UDS relay that lets `eval_scala`
  * user code (fully synchronous — it `spawnSync`s this helper) reach the host's
  * MCP servers within one eval.
  *
  * It performs ONE request→response round-trip: read the request JSON from
  * stdin, connect the `AUK_MCP_SOCK` bridge, write the request, read one response
  * line, print it, and exit. It loads NO WebAssembly — it is pure Node — so a
  * per-call spawn stays cheap (the spike measured ~28ms/call).
  *
  * This is the DEV shape, the exact twin of [[ReplArtifacts.BootstrapSource]]:
  * outside a SEA the host writes [[Source]] to a temp `.mjs` (via
  * [[writeDevHelper]]) and the worker spawns `node <that file>`. Inside a SEA
  * there is no sibling script to run, so the same logic lives behind the auk
  * binary's own `--mcp-call` entry branch (packageBinary's entry.mjs). The worker
  * (`library`'s `McpImpl`, Phase 3) chooses which by whether `AUK_MCP_HELPER_JS`
  * is set — mirroring `ReplArtifacts`' `AUK_REPL_WORKER_JS` (dev script) vs
  * `--repl-worker` (SEA branch) split exactly. Keep [[Source]] and that entry.mjs
  * branch in sync.
  *
  * The hard requirement (a spike lesson): flush stdout BEFORE exiting via
  * `process.stdout.write(line, () => process.exit(0))`. A bare `process.exit`
  * truncates a payload larger than the ~64KB pipe buffer. On any local failure
  * (missing socket, refused/closed connection) the helper still prints a
  * well-formed `{"ok":false,"error":...}` line and exits 0, so the worker-side
  * proxy always parses a structured result rather than seeing a bare non-zero
  * exit. */
object McpHelper:

  /** The env var carrying the dev helper `.mjs` path to a worker. Set in dev,
    * UNSET under SEA; the worker's `McpImpl` picks its `spawnSync` argv by this
    * var's presence (set ⇒ `[execPath, <path>]`; unset ⇒ `[execPath,
    * "--mcp-call"]`). Injection is Phase 4; this names the contract. */
  val HelperEnv: String = "AUK_MCP_HELPER_JS"

  /** Write the dev helper module to a stable temp path and return it. Rewritten
    * on every call; the content is constant, so concurrent writers are harmless
    * (mirrors [[ReplArtifacts]]'s bootstrap writer). */
  def writeDevHelper(): String =
    val path = NodePath.join(nodeTmpdir(), "auk-mcp-call.mjs")
    NodeFs.writeFileSync(path, Source, "utf8")
    path

  /** The helper's ES-module source. Authored once here; the SEA `--mcp-call`
    * branch in packageBinary's entry.mjs is its manually-synced twin. Written as
    * a raw triple-quoted string (no Scala escape processing), so the `"\n"`
    * literals below are real backslash-n in the emitted JS. Avoids `|` characters
    * so `stripMargin` only trims the leading margin. */
  val Source: String =
    """// Generated by auk: the --mcp-call round-trip helper (no WASM loaded).
      |import { createConnection } from "node:net";
      |
      |const emit = (line) => {
      |  // Flush BEFORE exiting: a bare process.exit() truncates payloads past the
      |  // ~64KB pipe buffer. The write callback fires once the pipe has drained.
      |  process.stdout.write(line + "\n", () => process.exit(0));
      |};
      |const fail = (msg) => emit(JSON.stringify({ ok: false, error: msg }));
      |
      |const sock = process.env.AUK_MCP_SOCK;
      |if (!sock) {
      |  fail("AUK_MCP_SOCK is not set");
      |} else {
      |  let input = "";
      |  process.stdin.setEncoding("utf8");
      |  process.stdin.on("data", (chunk) => { input += chunk; });
      |  process.stdin.on("end", () => {
      |    const conn = createConnection(sock);
      |    conn.setEncoding("utf8");
      |    let buf = "";
      |    let done = false;
      |    conn.on("connect", () => { conn.write(input.trim() + "\n"); });
      |    conn.on("data", (chunk) => {
      |      buf += chunk;
      |      const nl = buf.indexOf("\n");
      |      if (nl >= 0 && !done) {
      |        done = true;
      |        try { conn.destroy(); } catch (_) {}
      |        emit(buf.slice(0, nl));
      |      }
      |    });
      |    conn.on("error", (e) => {
      |      if (!done) {
      |        done = true;
      |        const m = e && e.message ? e.message : String(e);
      |        fail("MCP bridge connection failed: " + m);
      |      }
      |    });
      |    conn.on("close", () => {
      |      if (!done) {
      |        done = true;
      |        fail("MCP bridge closed the connection without responding");
      |      }
      |    });
      |  });
      |}
      |""".stripMargin
