package auk.agent

import gears.async.Async
import auk.generated.LibrarySource
import auk.runtime.repl.ReplPreamble

/** Composes the system prompt for the top-level interactive agent.
  *
  * The prompt has two parts, assembled into one stream of `##` markdown
  * sections:
  *
  *   - a **static** part — the identity and the fixed instruction sections
  *     ([[staticSections]]) that are the same every run; and
  *   - a **dynamic** part — [[dynamicSections]] whose bodies are gathered from
  *     the live session ([[PromptEnv]]) at start-up: the environment (working
  *     directory, model, git status) and any project-wide instructions
  *     (CLAUDE.md / AGENTS.md).
  *
  * New concerns slot in as another [[Section]] or [[DynamicSection]] without
  * touching the callers. The two static pieces that must never drift from the
  * code are pulled from their single sources of truth: the runtime library
  * interface is the embedded text of AukInterface.scala
  * ([[auk.generated.LibrarySource]], generated by build.sbt), and the session
  * preamble is the exact string [[auk.runtime.repl.ScalaRepl]] evaluates at
  * session start ([[ReplPreamble.Source]]).
  *
  * Sub-agents keep their own, narrower prompt ([[auk.runtime.SubAgent]]); this
  * one explains the eval_scala action surface — how the interactive engine does
  * file work by writing Scala rather than through dedicated read/edit/write
  * tools.
  */
object SystemPrompt:

  /** One titled block of the prompt, rendered as a `##` markdown section. */
  final case class Section(title: String, body: String)

  val Identity: String =
    "You are auk, an interactive coding agent running in the user's terminal. " +
      "You help with software engineering tasks — reading and changing code, " +
      "running commands, and answering questions about the project — using " +
      "the tools available to you. Be direct and concise; prefer acting over " +
      "describing what you would do."

  /** The fixed instruction sections, identical every run. */
  def staticSections: List[Section] = List(scalaEvaluation)

  /** The environment-derived sections, in render order. */
  def dynamicSections: List[DynamicSection] =
    List(DynamicSection.ProjectInfo, DynamicSection.ProjectInstructions)

  /** The static-only prompt: identity plus [[staticSections]], no environment
    * I/O. The safe default for headless/test callers and the [[Engine]]'s
    * fallback. */
  def default: String = render(Identity, staticSections)

  /** The full prompt for a live session: the static prompt followed by every
    * dynamic section that has something to contribute for `env`. */
  def build(env: PromptEnv)(using Async): String =
    val dyn = dynamicSections.flatMap(d => d.render(env).map(Section(d.title, _)))
    render(Identity, staticSections ++ dyn)

  def render(identity: String, sections: List[Section]): String =
    (identity :: sections.map(s => s"## ${s.title}\n\n${s.body}")).mkString("\n\n")

  private def scalaEvaluation: Section =
    Section(
      "Scala evaluation",
      s"""The eval_scala tool evaluates Scala 3 code in a persistent REPL session
         |(Scala.js on Node.js); definitions — vals, defs, classes, imports —
         |accumulate across calls, so later calls build on earlier ones.
         |
         |Writing Scala is how you act: there are no separate read/edit/write or
         |shell tools. File work goes through `lib.fs` / `lib.Path`, and shell
         |commands through `lib.shell`. The auk runtime library is preloaded, and
         |its interface is:
         |
         |```scala
         |${LibrarySource.interface}```
         |
         |Every session starts with this preamble already evaluated:
         |
         |```scala
         |${ReplPreamble.Source}
         |```
         |
         |so reach the library through `lib`. For example:
         |
         |```scala
         |lib.Path("build.sbt").asFile.read()           // print a file as numbered lines
         |lib.fs.cwd.asDir.grep("TODO", "**/*.scala")   // search the tree
         |val f = lib.Path("notes.md").asFile           // write, then edit, a file
         |f.write("# Notes")
         |f.replace("# Notes", "# Project notes")
         |lib.shell.run("git", "status", "--short")     // run a program (captured result)
         |val sbt = lib.shell.command("sbt")            // a reusable, validated handle
         |sbt.execute("test")
         |```
         |
         |Do file operations through `lib.fs` / `lib.Path`, not the shell: programs
         |like `rm`, `ls`, `mv`, `mkdir`, `cat`, and `touch` are rejected by
         |`lib.shell` — use the library's structured file API instead.
         |
         |The code runs on Scala.js under Node, so JavaScript and Node APIs are
         |reachable through scala.scalajs.js interop and a global `require`.
         |Compile and runtime errors come back as the tool result, so fix and
         |retry. The preamble is re-evaluated when a session restarts; your own
         |definitions are not.""".stripMargin
    )
