package auk.agent

import auk.generated.LibrarySource
import auk.runtime.repl.ReplPreamble

/** Composes the system prompt for the top-level interactive agent.
  *
  * The prompt is assembled from [[Section]]s rendered as markdown, so new
  * concerns (environment, project conventions, …) can be added without
  * touching the callers. The two pieces that must never drift from the code
  * are pulled from their single sources of truth: the runtime library
  * interface is the embedded text of AukInterface.scala
  * ([[auk.generated.LibrarySource]], generated by build.sbt), and the session
  * preamble is the exact string [[auk.runtime.repl.ScalaRepl]] evaluates at
  * session start ([[ReplPreamble.Source]]).
  *
  * Sub-agents keep their own, narrower prompt ([[auk.runtime.SubAgent]]); this
  * one describes the full toolset of the interactive engine, eval_scala
  * included.
  */
object SystemPrompt:

  /** One titled block of the prompt, rendered as a `##` markdown section. */
  final case class Section(title: String, body: String)

  val Identity: String =
    "You are auk, an interactive coding agent running in the user's terminal. " +
      "You help with software engineering tasks — reading and changing code, " +
      "running commands, and answering questions about the project — using " +
      "the tools available to you. Be direct and concise; prefer acting over " +
      "describing what you would do."

  /** The default prompt for the interactive engine. */
  def default: String = render(Identity, sections)

  def render(identity: String, sections: List[Section]): String =
    (identity :: sections.map(s => s"## ${s.title}\n\n${s.body}")).mkString("\n\n")

  def sections: List[Section] = List(scalaEvaluation)

  private def scalaEvaluation: Section =
    Section(
      "Scala evaluation",
      s"""The eval_scala tool evaluates Scala 3 code in a persistent REPL session
         |(Scala.js on Node.js); definitions accumulate across calls. The auk
         |runtime library is preloaded into every session. Its interface:
         |
         |```scala
         |${LibrarySource.interface}```
         |
         |Each session starts with this preamble already evaluated:
         |
         |```scala
         |${ReplPreamble.Source}
         |```
         |
         |so call the library through `lib`, e.g. `lib.hello("world")`. The
         |preamble is re-evaluated automatically when a session restarts; your
         |own definitions are not.""".stripMargin
    )
