#!/usr/bin/env bash
#
# Local publishing pipeline for auk.
#
#   1. Publishes the project to your local Ivy repo (~/.ivy2/local) via
#      `sbt publishLocal`.
#   2. Installs a thin `auk` launcher onto your PATH (in coursier's own bin
#      dir) that runs the freshly-published artifact via `cs launch`.
#
# After running this once, the day-to-day loop is just:
#
#   sbt publishLocal   # rebuild & republish
#   auk                # runs the latest published build (no reinstall needed)
#
# The launcher uses `cs launch`, which re-resolves on every run, so a new
# `publishLocal` is picked up automatically. (A `cs bootstrap` launcher, by
# contrast, is pinned at build time and would need rebuilding each publish.)
#
set -euo pipefail

cd "$(dirname "$0")/.."

# Coordinate published by `sbt publishLocal`. Keep in sync with build.sbt
# (organization %% name % version). `_3` is the Scala 3 suffix.
COORD="com.example:auk_3:0.1.0-SNAPSHOT"
MAIN_CLASS="auk.main"

echo ">> sbt publishLocal"
sbt publishLocal

# Install the launcher next to `cs` itself, which `cs setup` already put on PATH.
BIN_DIR="$(dirname "$(command -v cs)")"
LAUNCHER="$BIN_DIR/auk"

cat > "$LAUNCHER" <<EOF
#!/usr/bin/env sh
# Auto-generated by scripts/install.sh — runs the latest \`sbt publishLocal\` build.
# --ttl 0s forces coursier to re-check the SNAPSHOT each run so new publishes
# are picked up immediately. ivy2Local is in coursier's default repositories.
exec cs launch --ttl 0s "$COORD" -M "$MAIN_CLASS" -- "\$@"
EOF
chmod +x "$LAUNCHER"

echo ">> installed launcher: $LAUNCHER"
echo ">> run it with: auk"
