#!/usr/bin/env bash
#
# Build & install pipeline for auk (Scala.js / WebAssembly on Bun).
#
#   1. Installs the npm SDK dependencies (`bun install`).
#   2. Compiles the project to WebAssembly (`sbt fastLinkJS`).
#   3. Installs a thin `auk` launcher onto your PATH that runs the freshly
#      linked build on Bun.
#
# After running this once, the day-to-day loop is just:
#
#   sbt fastLinkJS   # recompile to Wasm  (or `sbt ~fastLinkJS` to watch)
#   auk              # runs the latest linked build (no reinstall needed)
#
set -euo pipefail

cd "$(dirname "$0")/.."
PROJECT_DIR="$(pwd)"

# The Scala.js linker output (a tiny ESM loader + the .wasm beside it). The
# launcher runs this directly; Bun resolves the npm SDKs from ./node_modules and
# loads ./main.wasm relative to the entry, regardless of the caller's cwd.
ENTRY="$PROJECT_DIR/target/scala-3.8.3/auk-fastopt/main.js"

command -v bun >/dev/null 2>&1 || { echo "error: 'bun' not found — install from https://bun.sh" >&2; exit 1; }
command -v sbt >/dev/null 2>&1 || { echo "error: 'sbt' not found — install via 'cs setup'" >&2; exit 1; }

echo ">> bun install (npm SDKs)"
bun install

echo ">> sbt fastLinkJS (compile to WebAssembly)"
sbt fastLinkJS

echo ">> patch loader (Bun/JSC js-string builtins workaround)"
bash "$PROJECT_DIR/scripts/patch-loader.sh"

# Install the launcher next to `cs` (already on PATH from `cs setup`), else next
# to `bun`.
if BIN_DIR="$(dirname "$(command -v cs 2>/dev/null)")" && [ -n "${BIN_DIR:-}" ] && [ -d "$BIN_DIR" ]; then
  :
else
  BIN_DIR="$(dirname "$(command -v bun)")"
fi
LAUNCHER="$BIN_DIR/auk"

LOADER="$PROJECT_DIR/target/scala-3.8.3/auk-fastopt/__loader.js"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env sh
# Auto-generated by scripts/install.sh — runs the latest \`sbt fastLinkJS\`
# Scala.js/Wasm build on Bun. Rebuild loop: \`sbt fastLinkJS\`, then \`auk\`.
# Self-heals a JavaScriptCore (Bun) js-string-builtins bug that blanks
# String.split's last segment; idempotent, re-applies after each relink.
[ -f "$LOADER" ] && perl -0pi -e 's/builtins:\s*\["js-string"\]/builtins: []/' "$LOADER" 2>/dev/null
exec bun run "$ENTRY" "\$@"
EOF
chmod +x "$LAUNCHER"

echo ">> installed launcher: $LAUNCHER"
echo ">> run it with: auk   (rebuild loop: 'sbt fastLinkJS' then 'auk')"
