package auk.grep.bench

import scala.scalajs.js

import auk.grep.bench.Bench.{JunkWords, fs, join, os}

/** The XL tier's corpus: a monorepo-scale tree, generated on demand.
  *
  * `sbt grepBench`'s two corpora (24 MB / 52 MB) are sized to make a bench run
  * cheap, which also makes them far too small to answer stage 6's question —
  * how a single-threaded engine compares to a *parallel* ripgrep once a tree is
  * big enough for core count to matter. This one is built for that measurement
  * and nothing else: ~50k source-like files in a nested tree, ~1.1 GB, plus a
  * gitignored junk layer so the walk row and rg's ignore handling stay
  * comparable with the dirty corpus.
  *
  * It is **never** generated by `sbt grepBench`; only `sbt grepBenchXL` asks for
  * it. First run writes it (a minute or so) and prints how to reclaim the disk;
  * later runs read the MANIFEST and reuse it.
  *
  * **Determinism** follows the same rules as the other two corpora: one seeded
  * LCG, no clock, no randomness, fixed iteration order — so the bytes are a pure
  * function of [[Tag]], and the planted match counts recorded in the MANIFEST
  * are exact rather than statistical. The LCG is this object's own, never
  * [[Bench]]'s, so generating the XL corpus cannot perturb the other two.
  *
  * **Shape** (all rates documented where they are declared):
  *   - a recursive tree, fanout 2-5 and a few files at each interior level, so
  *     files land at mixed depths (~4-7) rather than one uniform layer;
  *   - file sizes mostly 2-30 KB with a long tail to ~3 MB, averaging ~20 KB;
  *   - `node_modules/`, `target/` and `dist/` junk under a root `.gitignore`
  *     with a `.git/` stub, written from [[Bench.JunkWords]] — the vocabulary
  *     that matches none of the three benchmark patterns, so junk contributes
  *     zero matches and auk and rg must still agree exactly.
  *
  * **Needles** are planted at rates chosen for the *match volume* each row
  * should exercise, not for realism: a handful for the rare literal, ~10k for
  * the regex, ~170k for the common word. The common-word rate is deliberately
  * ~1 line in 128 — a real source tree would say "return" far more often, but
  * a row returning millions of matches would measure result marshalling rather
  * than search, and the honest scale test for the result object is a few
  * hundred thousand rows, not a few million.
  */
object XlCorpus:

  /** Bump on any change to the generated bytes: it names the cache directory,
    * so a new tag simply generates alongside the old one. */
  val Tag = "xl-v1"

  private val Seed = 0x6b1f3a7

  // -- scale ------------------------------------------------------------------

  /** Files in the searchable tree. ~20 KB average => ~1 GB of real content. */
  private val RealFiles = 50000
  private val TopDirs = 12
  private val MaxDepth = 7
  /** A subtree with no more than this many files stops splitting and becomes a
    * leaf directory — the knob that sets how deep the tree actually goes. */
  private val LeafBudget = 40

  // junk layer: ~6.2k files, ~150 MB, all of it gitignored
  private val NmPkgDirs = 300
  private val NmFilesPerPkg = 20
  private val TargetFiles = 200
  private val BlobBytes = 32 * 1024 * 1024
  private val MinJsBytes = 8 * 1024 * 1024

  // -- needle rates -----------------------------------------------------------

  private val Needle = "aukGrepBenchNeedle"
  /** The rare literal goes into every 4096th file: 12 of 50000, same handful as
    * the clean corpus, now hidden in ~1000x the bytes. */
  private val RareEveryFiles = 4096
  /** "return" on one line in 128 => ~170k matching lines. */
  private val CommonEveryLines = 128
  /** `handler_<n>` on one line in 2048 => ~10k matching lines, and — the reason
    * for this particular rate — a required-literal hit in only ~20% of files,
    * so stage 5's prefilter stays *on* for this row instead of giving up as it
    * does on the small corpora. */
  private val RegexEveryLines = 2048

  // -- vocabulary -------------------------------------------------------------

  // Source-like identifiers with no "return", no "handler" and no needle
  // substring anywhere: every match in the corpus is planted, so the counts are
  // exactly the counters below.
  private[bench] val Words = Array(
    "val", "def", "given", "using", "final", "lazy", "inline", "trait",
    "object", "extends", "params", "result", "buffer", "index", "stream",
    "worker", "engine", "parse", "walk", "entry", "flush", "cache", "token",
    "scope", "yield", "await", "batch", "frame", "queue", "shard", "probe",
    "trace", "guard", "merge", "split", "close", "decode", "encode", "offset",
    "cursor", "region", "symbol", "module", "linker", "driver", "socket",
    "packet", "record", "slice", "chunk", "digest", "commit"
  )

  private val DirWords = Array(
    "core", "util", "runtime", "codec", "proto", "store", "net", "sync",
    "model", "view", "shell", "infra", "lang", "tools", "wire", "graph"
  )

  private val Exts = Array("scala", "ts", "py", "go", "java", "rs", "md")

  private val LinePoolSize = 8192

  // -- deterministic state ----------------------------------------------------

  private var seed: Int = Seed
  private def nextInt(bound: Int): Int =
    seed = seed * 1664525 + 1013904223
    (seed >>> 8) % bound

  private var globalLine = 0
  private var fileIdx = 0
  private var files = 0
  private var bytes = 0.0
  private var rare = 0
  private var common = 0
  private var regex = 0
  private var dirs = 0
  private var maxSeenDepth = 0
  private var depthHist = Array.fill(MaxDepth + 2)(0)
  private var nextProgress = 0

  private def reset(): Unit =
    seed = Seed
    globalLine = 0
    fileIdx = 0
    files = 0
    bytes = 0.0
    rare = 0
    common = 0
    regex = 0
    dirs = 0
    maxSeenDepth = 0
    depthHist = Array.fill(MaxDepth + 2)(0)
    nextProgress = 10000

  // -- content ----------------------------------------------------------------

  /** A fixed pool of lines, drawn from per file. Building 22M lines word by word
    * would dominate generation time for no benefit: neither engine can tell the
    * difference between drawn and freshly-built lines, and both the byte volume
    * and the planted match counts are unaffected. */
  private def buildLinePool(): Array[String] =
    val pool = new Array[String](LinePoolSize)
    var i = 0
    while i < LinePoolSize do
      val sb = new StringBuilder
      var indent = nextInt(4) * 2
      while indent > 0 do
        sb.append(' ')
        indent -= 1
      val n = 3 + nextInt(9)
      var w = 0
      while w < n do
        if w > 0 then sb.append(' ')
        sb.append(Words(nextInt(Words.length)))
        w += 1
      pool(i) = sb.toString
      i += 1
    pool

  private var linePool: Array[String] = Array.empty

  /** A fingerprint of the line pool at the fixed seed — the whole of the LCG,
    * the vocabulary and the line shape, folded into one string. Pinning it in a
    * test pins the generated bytes without writing 1.1 GB of them: any change
    * that would silently give [[Tag]] a different corpus moves this first. */
  private[bench] def linePoolFingerprint(): String =
    reset()
    val pool = buildLinePool()
    var chars = 0
    var h = 0
    for l <- pool do
      chars += l.length
      var i = 0
      while i < l.length do
        h = h * 31 + l.charAt(i).toInt
        i += 1
    s"${pool.length}:$chars:${Integer.toHexString(h)}"

  /** Draw lines until `targetBytes`, planting the common word and the regex
    * token on their fixed global-line strides. A line can carry both; each
    * pattern still counts it once, which is what rg reports. */
  private def realContent(targetBytes: Int, plantNeedle: Boolean): String =
    val sb = new StringBuilder
    while sb.length < targetBytes do
      sb.append(linePool(nextInt(LinePoolSize)))
      if globalLine % CommonEveryLines == 7 then
        sb.append(" return")
        common += 1
      if globalLine % RegexEveryLines == 11 then
        sb.append(" handler_").append(globalLine % 977)
        regex += 1
      sb.append('\n')
      globalLine += 1
    if plantNeedle then
      sb.append("// ").append(Needle).append(" marker\n")
      rare += 1
    sb.toString

  private def junkContent(targetBytes: Int): String =
    val sb = new StringBuilder
    while sb.length < targetBytes do
      val n = 4 + nextInt(8)
      var w = 0
      while w < n do
        if w > 0 then sb.append(' ')
        sb.append(JunkWords(nextInt(JunkWords.length)))
        w += 1
      sb.append('\n')
    sb.toString

  /** Mostly small source-like files with a long tail: 98.5% land in 2-30 KB,
    * 1.4% in 30-300 KB, and 1 in 1000 between 0.5 and 3 MB. */
  private def realBytes(): Int =
    val r = nextInt(1000)
    if r < 985 then 2048 + nextInt(28 * 1024)
    else if r < 999 then 30 * 1024 + nextInt(270 * 1024)
    else 512 * 1024 + nextInt(2560 * 1024)

  // -- writing ----------------------------------------------------------------

  private def mkdir(p: String): Unit =
    fs.mkdirSync(p, js.Dynamic.literal(recursive = true))
    dirs += 1

  private def write(p: String, content: String): Unit =
    fs.writeFileSync(p, content, "utf8")
    files += 1
    bytes += content.length
    if files >= nextProgress then
      println(f"  ... $files%d files, ${bytes / 1024 / 1024}%.0f MB")
      nextProgress += 10000

  private def writeRealFiles(dir: String, count: Int, depth: Int): Unit =
    var f = 0
    while f < count do
      val name = s"${DirWords(nextInt(DirWords.length))}$f.${Exts(nextInt(Exts.length))}"
      val plant = fileIdx % RareEveryFiles == 1000
      fileIdx += 1
      write(join(dir, name), realContent(realBytes(), plant))
      depthHist(math.min(depth, MaxDepth + 1)) += 1
      f += 1

  /** Split `budget` files over a subtree: a few files here, then 2-5 children
    * sharing the rest with ±30% jitter, until a subtree is small enough (or deep
    * enough) to become a leaf. */
  private def genTree(dir: String, depth: Int, budget: Int): Unit =
    if depth > maxSeenDepth then maxSeenDepth = depth
    mkdir(dir)
    if depth >= MaxDepth || budget <= LeafBudget then writeRealFiles(dir, budget, depth)
    else
      val here = math.min(2 + nextInt(5), budget)
      writeRealFiles(dir, here, depth)
      var remaining = budget - here
      val fanout = 2 + nextInt(4)
      var i = 0
      while i < fanout && remaining > 0 do
        val even = remaining / (fanout - i)
        val share =
          if i == fanout - 1 then remaining
          else math.max(1, math.min(remaining, even * (70 + nextInt(61)) / 100))
        genTree(join(dir, s"${DirWords(nextInt(DirWords.length))}$i"), depth + 1, share)
        remaining -= share
        i += 1

  private def genJunk(root: String): Unit =
    write(join(root, ".gitignore"), "node_modules/\ntarget/\ndist/\n")
    mkdir(join(root, ".git"))
    write(join(join(root, ".git"), "HEAD"), "ref: refs/heads/main\n")

    var pkg = 0
    while pkg < NmPkgDirs do
      val dir = join(join(root, "node_modules"), s"pkg$pkg")
      mkdir(dir)
      var f = 0
      while f < NmFilesPerPkg do
        write(join(dir, s"mod$f.js"), junkContent(5 * 1024 + nextInt(20 * 1024)))
        f += 1
      pkg += 1

    // One minified-style monster: a single line, no newline anywhere.
    val minjs = new StringBuilder
    while minjs.length < MinJsBytes do
      if minjs.length > 0 then minjs.append(';')
      minjs.append(JunkWords(nextInt(JunkWords.length)))
    write(join(join(root, "node_modules"), "lib.min.js"), minjs.toString)

    mkdir(join(root, "target"))
    var t = 0
    while t < TargetFiles do
      write(join(join(root, "target"), s"build$t.log"), junkContent(50 * 1024 + nextInt(100 * 1024)))
      t += 1

    // dist/blob.bin: NUL-marked binary, built programmatically so no raw NUL
    // byte appears in this source (see Bench's copy). latin1 keeps one byte per
    // char, so the size is exact and the NULs survive.
    mkdir(join(root, "dist"))
    val block = new StringBuilder
    var j = 0
    while j < 1024 do
      block.append((if j % 64 == 0 then 0 else j % 256).toChar)
      j += 1
    val blockStr = block.toString
    val blob = new StringBuilder
    while blob.length < BlobBytes do blob.append(blockStr)
    val blobStr = blob.toString
    fs.writeFileSync(join(join(root, "dist"), "blob.bin"), blobStr, "latin1")
    files += 1
    bytes += blobStr.length

  // -- manifest ---------------------------------------------------------------

  /** What a generated corpus is, recorded so a cached run reports the same
    * numbers — including the planted match counts, which the bench checks the
    * engines against on every row. */
  final case class Stats(
      root: String,
      files: Int,
      bytes: Double,
      realFiles: Int,
      junkFiles: Int,
      dirs: Int,
      maxDepth: Int,
      depthHist: List[Int],
      rare: Int,
      common: Int,
      regex: Int,
      cached: Boolean
  )

  private def manifestText(root: String): String =
    val sb = new StringBuilder
    sb.append("files ").append(files).append('\n')
    sb.append("bytes ").append(bytes.toLong.toString).append('\n')
    sb.append("realFiles ").append(RealFiles).append('\n')
    sb.append("junkFiles ").append(files - RealFiles).append('\n')
    sb.append("dirs ").append(dirs).append('\n')
    sb.append("maxDepth ").append(maxSeenDepth).append('\n')
    sb.append("depthHist ").append(depthHist.mkString(",")).append('\n')
    sb.append("rare ").append(rare).append('\n')
    sb.append("common ").append(common).append('\n')
    sb.append("regex ").append(regex).append('\n')
    sb.toString

  private def parse(root: String, text: String): Stats =
    val kv = text.linesIterator
      .map(_.trim)
      .filter(_.nonEmpty)
      .map { l =>
        val i = l.indexOf(' ')
        (l.substring(0, i), l.substring(i + 1))
      }
      .toMap
    Stats(
      root = root,
      files = kv("files").toInt,
      bytes = kv("bytes").toDouble,
      realFiles = kv("realFiles").toInt,
      junkFiles = kv("junkFiles").toInt,
      dirs = kv("dirs").toInt,
      maxDepth = kv("maxDepth").toInt,
      depthHist = kv("depthHist").split(',').toList.map(_.toInt),
      rare = kv("rare").toInt,
      common = kv("common").toInt,
      regex = kv("regex").toInt,
      cached = true
    )

  // -- entry point ------------------------------------------------------------

  /** Generate (or reuse) the XL corpus. */
  def generate(): Stats =
    val root = join(os.tmpdir().asInstanceOf[String], s"auk-grep-bench-$Tag")
    val manifest = join(root, "MANIFEST")
    if fs.existsSync(manifest).asInstanceOf[Boolean] then
      parse(root, fs.readFileSync(manifest, "utf8").asInstanceOf[String])
    else
      println(s"generating the XL corpus at $root (this takes a minute; it is cached afterwards)")
      reset()
      fs.rmSync(root, js.Dynamic.literal(recursive = true, force = true))
      mkdir(root)
      linePool = buildLinePool()

      // Top-level modules share the file budget with the same ±30% jitter as
      // the interior levels, so they are not uniform either.
      var remaining = RealFiles
      var t = 0
      while t < TopDirs do
        val even = remaining / (TopDirs - t)
        val share =
          if t == TopDirs - 1 then remaining
          else math.max(1, math.min(remaining, even * (70 + nextInt(61)) / 100))
        genTree(join(root, s"${DirWords(t % DirWords.length)}$t"), 1, share)
        remaining -= share
        t += 1

      genJunk(root)
      fs.writeFileSync(manifest, manifestText(root), "utf8")
      parse(root, manifestText(root)).copy(cached = false)
